#include <Wire.h>
#include <math.h>
#include "xgb_model.h"  // Custom compact XGBoost model (3-class, softmax)

#define MPU_ADDR 0x68

// ===== StandardScaler values from fall_detection_scaler.pkl =====
// Generated by: python3 export_scaler_values.py
float scaler_mean[]  = {1.0470912904f, 1.5079582134f, 0.7931952830f, 0.1847859162f, 29.9313368265f, 59.9003295838f, 95.7493172296f, 25.8872232637f, 59.3151603700f};
float scaler_scale[] = {0.1479218672f, 1.1107187337f, 0.2717388014f, 0.3221384145f, 37.9102303414f, 92.1114553187f, 30.3905397275f, 34.0920593883f, 57.3864083179f};

#define NUM_FEATURES   9
#define WINDOW_SIZE    80
#define THRESHOLD      0.6f
#define SAMPLE_RATE_HZ 200
#define INTERVAL_MS    (1000 / SAMPLE_RATE_HZ)

// Buffers
float accel_x[WINDOW_SIZE], accel_y[WINDOW_SIZE], accel_z[WINDOW_SIZE];
float gyro_x[WINDOW_SIZE],  gyro_y[WINDOW_SIZE],  gyro_z[WINDOW_SIZE];

int sample_idx = 0;
unsigned long lastSampleTime = 0;

// Raw read variables
int16_t AccX, AccY, AccZ;
int16_t GyroX, GyroY, GyroZ;

void setup() {
  Serial.begin(115200);
  delay(2000);

  Wire.begin(21, 22);

  // Wake up MPU
  Wire.beginTransmission(MPU_ADDR);
  Wire.write(0x6B);
  Wire.write(0);
  Wire.endTransmission(true);

  // ===== CRITICAL: Set accelerometer range to ±16G =====
  // SisFall was recorded at ±16G. Default ±2G clips at 2G,
  // making all falls look the same. Register 0x1C, value 0x18 = ±16G.
  Wire.beginTransmission(MPU_ADDR);
  Wire.write(0x1C);       // ACCEL_CONFIG register
  Wire.write(0x18);       // ±16G (AFS_SEL = 3)
  Wire.endTransmission(true);

  // ===== Set gyroscope range to ±2000°/s =====
  // Matches SisFall's ITG-3200 range. Register 0x1B, value 0x18 = ±2000°/s.
  Wire.beginTransmission(MPU_ADDR);
  Wire.write(0x1B);       // GYRO_CONFIG register
  Wire.write(0x18);       // ±2000°/s (FS_SEL = 3)
  Wire.endTransmission(true);

  Serial.println("MPU6050 Initialized: 200Hz, ±16G, ±2000°/s");
  Serial.println("XGBoost 3-class model loaded (50 estimators, softmax)");
  pinMode(LED_BUILTIN, OUTPUT);
}

// ===== Feature extraction =====
void extract_features(float* features) {
  float svm[WINDOW_SIZE], gvm[WINDOW_SIZE], tilt[WINDOW_SIZE];
  float svm_sum = 0, svm_max = -1e9, svm_min = 1e9;
  float gvm_sum = 0, gvm_max = -1e9;
  float tilt_sum = 0, tilt_max = -1e9, tilt_min = 1e9;

  for (int i = 0; i < WINDOW_SIZE; i++) {
    svm[i]  = sqrt(accel_x[i]*accel_x[i] + accel_y[i]*accel_y[i] + accel_z[i]*accel_z[i]);
    gvm[i]  = sqrt(gyro_x[i]*gyro_x[i]   + gyro_y[i]*gyro_y[i]   + gyro_z[i]*gyro_z[i]);
    tilt[i] = atan2(sqrt(accel_x[i]*accel_x[i] + accel_y[i]*accel_y[i]), accel_z[i]) * 57.2958f;

    svm_sum += svm[i];   svm_max = max(svm_max, svm[i]);   svm_min = min(svm_min, svm[i]);
    gvm_sum += gvm[i];   gvm_max = max(gvm_max, gvm[i]);
    tilt_sum += tilt[i]; tilt_max = max(tilt_max, tilt[i]); tilt_min = min(tilt_min, tilt[i]);
  }

  float svm_avg = svm_sum / WINDOW_SIZE;
  float variance = 0;
  for (int i = 0; i < WINDOW_SIZE; i++) variance += (svm[i] - svm_avg) * (svm[i] - svm_avg);
  float svm_std = sqrt(variance / WINDOW_SIZE);

  features[0] = svm_avg;
  features[1] = svm_max;
  features[2] = svm_min;
  features[3] = svm_std;
  features[4] = gvm_sum / WINDOW_SIZE;
  features[5] = gvm_max;
  features[6] = tilt_sum / WINDOW_SIZE;
  features[7] = tilt_max - tilt_min;
  features[8] = (svm_std > 0.001f) ? svm_avg / svm_std : 0.0f;
}

// ===== Apply StandardScaler =====
void apply_scaler(float* features) {
  for (int i = 0; i < NUM_FEATURES; i++) {
    features[i] = (features[i] - scaler_mean[i]) / scaler_scale[i];
  }
}

// ===== MAIN LOOP =====
void loop() {

  if (millis() - lastSampleTime >= INTERVAL_MS) {
    lastSampleTime = millis();

    // Read 14 bytes from MPU6050
    Wire.beginTransmission(MPU_ADDR);
    Wire.write(0x3B);
    Wire.endTransmission(false);
    Wire.requestFrom(MPU_ADDR, 14, true);

    AccX = Wire.read()<<8 | Wire.read();
    AccY = Wire.read()<<8 | Wire.read();
    AccZ = Wire.read()<<8 | Wire.read();

    Wire.read(); Wire.read(); // skip temp

    GyroX = Wire.read()<<8 | Wire.read();
    GyroY = Wire.read()<<8 | Wire.read();
    GyroZ = Wire.read()<<8 | Wire.read();

    // Convert to G and deg/s (±16G and ±2000°/s ranges)
    // ±16G  → sensitivity = 2048 LSB/G
    // ±2000 → sensitivity = 16.4 LSB/(°/s)
    accel_x[sample_idx] = AccX / 2048.0f;
    accel_y[sample_idx] = AccY / 2048.0f;
    accel_z[sample_idx] = AccZ / 2048.0f;

    gyro_x[sample_idx]  = GyroX / 16.4f;
    gyro_y[sample_idx]  = GyroY / 16.4f;
    gyro_z[sample_idx]  = GyroZ / 16.4f;

    sample_idx++;

    // ===== Window ready → run inference =====
    if (sample_idx >= WINDOW_SIZE) {

      float features[NUM_FEATURES];
      float output[3];  // [ADL_prob, PreFall_prob, Fall_prob]

      extract_features(features);
      apply_scaler(features);

      // XGBoost inference → output[0..2] = softmax probabilities
      xgb_predict(features, output);

      // Decision logic using probability thresholds
      if (output[2] >= THRESHOLD) {
        Serial.printf("!!! FALL !!! (prob=%.2f)\n", output[2]);
        digitalWrite(LED_BUILTIN, HIGH);
      } else if (output[1] >= THRESHOLD) {
        Serial.printf("Pre-Fall (prob=%.2f)\n", output[1]);
      } else {
        Serial.printf("Normal — ADL=%.2f Pre=%.2f Fall=%.2f\n", output[0], output[1], output[2]);
        digitalWrite(LED_BUILTIN, LOW);
      }

      // Slide window: 50% overlap (keep last 40 samples)
      for (int i = 0; i < 40; i++) {
        accel_x[i] = accel_x[i+40];
        accel_y[i] = accel_y[i+40];
        accel_z[i] = accel_z[i+40];
        gyro_x[i]  = gyro_x[i+40];
        gyro_y[i]  = gyro_y[i+40];
        gyro_z[i]  = gyro_z[i+40];
      }

      sample_idx = 40;
    }
  }
}